# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import yaml
from typing import List

from infinitebench import PROMPT_TEMPLATES

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

TASKS = [
    'passkey',
    'number_string',
    'kv_retrieval',
    'longbook_sum_eng',
    'longbook_choice_eng',
    'longbook_qa_eng',
    'longbook_qa_chn',
    'math_find',
    'math_calc',
    'code_run',
    'code_debug',
    'longdialogue_qa_eng',
]


def define_cmd_arguments():
    parser = argparse.ArgumentParser()

    # Model Parameters
    parser.add_argument('-n', '--model_name', required=True, help='experiment name prefix')
    parser.add_argument('-p', '--model_path', required=True, help='model path')
    parser.add_argument(
        '-pc',
        '--prompt_config',
        required=True,
        choices=PROMPT_TEMPLATES.keys(),
        help='prompt template config name. options from `infinitebench/data/template.py`',
    )

    # Attention Configuration
    parser.add_argument('-a', '--attn_type', default='star', help='attention type')
    parser.add_argument('-bs', '--block_size', type=int, default=-1, help='context block size')
    parser.add_argument('-as', '--anchor_block_size', type=int, default=-1, help='anchor block size')

    # Sequence Length and Tasks
    parser.add_argument('-l', '--max_seq_length', type=int, default=131072, help='max sequence length')
    parser.add_argument('-t', '--tasks', default=TASKS, nargs='+', choices=TASKS, help='tasks')
    parser.add_argument(
        '-d',
        '--pregen_data_dir',
        required=True,
        help='pre-generated data directory in the `dataset` folder. Use `infinitebench/data/prepare.py` to generate it.',
    )

    # Distributed Inference Parameters
    parser.add_argument(
        '-nn', '--num_nodes', type=int, default=1, help='number of nodes. For dense attention, default is set to 1.'
    )
    parser.add_argument('-np', '--nproc_per_node', type=int, default=None, help='number of processes per node')

    # Logging
    parser.add_argument(
        '--output_dir',
        default=os.path.join(BASE_DIR, 'results'),
        help='results directory',
    )

    return parser.parse_args()


def submit_job(cmd, log_dir, filename):
    # Save the command to a file
    os.makedirs(log_dir, exist_ok=True)
    with open(os.path.join(log_dir, filename), 'w') as f:
        f.write(cmd)

    # Submit the job
    os.system(f'cd {BASE_DIR}; {cmd}')


def main(
    model_path: str,
    attn_type: str,
    block_size: int,
    anchor_block_size: int,
    prompt_config: str,
    max_seq_length: int,
    tasks: List[str],
    nproc_per_node: int,
    output_dir: str,
    pregen_data_dir: str,
    num_nodes: int = 1,
):
    if 'star' in attn_type:
        assert (
            block_size >= anchor_block_size
        ), f'block_size ({block_size}) must be greater than anchor_block_size ({anchor_block_size})'

        if block_size + anchor_block_size > max_seq_length:
            raise ValueError(
                f'block_size + anchor_block_size ({block_size + anchor_block_size}) '
                f'must be less than or equal to seq_length ({max_seq_length}).'
            )

    # Path to the pre-generated data (use `infinitebench/data/prepare.py` to generate it)
    pregen_data_dir = os.path.join(BASE_DIR, 'dataset', pregen_data_dir)

    # Inference Parameters
    stop_words = ','.join(PROMPT_TEMPLATES[prompt_config]['stop_words'])
    with open(os.path.join(BASE_DIR, 'infinitebench', 'inference_config.yaml')) as f:
        tokens_to_generate = yaml.safe_load(f)['tokens_to_generate']

    # Depending on the sequence length and the block size, adjust the number of processes
    if attn_type != 'dense':
        nproc_per_node_seq_len = min(
            nproc_per_node, (max_seq_length // block_size) if block_size > 0 else nproc_per_node
        )
        inference_executor = f'torchrun --nnodes={num_nodes} --nproc_per_node={nproc_per_node_seq_len}'
    else:
        inference_executor = 'python'

    results_dir = os.path.join(output_dir, f'{max_seq_length}')
    log_dir = os.path.join(results_dir, 'logs')
    os.makedirs(log_dir, exist_ok=True)

    # Generate predictions for each task
    for task in tasks:
        task_log_dir = os.path.join(log_dir, task)

        # The data is expected to be pre-generated by `infinitebench/data/prepare.py`
        task_data_file = os.path.join(pregen_data_dir, f'{task}.jsonl')
        if not os.path.exists(task_data_file):
            print(
                f'Data file not found for task `{task}`: {task_data_file}. '
                'Generate it with `infinitebench/data/prepare.py`. Skipping...'
            )
            continue

        # Run response generation
        task_gen_cmd = (
            f'{inference_executor} run_star_attn_inference.py '
            f'--model_path {model_path} '
            f'--attn_type {attn_type} '
            f'--block_size {block_size} '
            f'--anchor_block_size {anchor_block_size} '
            f'--tokens_to_generate {tokens_to_generate[task]} '
            f'--input_path {task_data_file} '
            f'--output_path {os.path.join(results_dir, task)}.jsonl '
            f'--stop_words "{stop_words}" '
            f'--use_cache'
        )
        print(f'\nRunning:\n{task_gen_cmd}')
        submit_job(task_gen_cmd, task_log_dir, 'generate_predictions.sh')

    # Run response scoring
    eval_cmd = f'python infinitebench/evaluate_responses.py --result_dir {results_dir}'
    print(f'\nRunning:\n{eval_cmd}')
    submit_job(eval_cmd, log_dir, 'evaluate_responses.sh')


if __name__ == '__main__':
    # Parse command line arguments
    args = define_cmd_arguments()

    # Validate star attention parameters
    if 'star' in args.attn_type:
        assert args.block_size > 0, 'block_size must be greater than 0'

    # Validate star and ring attention parameters
    if args.attn_type != 'dense':
        assert args.nproc_per_node is not None and args.nproc_per_node > 0, 'nproc_per_node must be greater than 0'
        assert args.num_nodes > 0, 'num_nodes must be greater than 0'

    # Validate model path
    if not os.path.exists(args.model_path):
        raise FileNotFoundError(f'{args.model_path} not found')

    # Setup the model name and output directory
    model_name_suffix = ''
    if 'star' in args.attn_type:
        anchor_block_size = args.anchor_block_size if args.anchor_block_size > 0 else args.block_size
        anchor_block_size_repr = (
            f'{anchor_block_size}' if anchor_block_size < 1024 else f'{anchor_block_size // 1024}k'
        )
        block_size_repr = f'{args.block_size}' if args.block_size < 1024 else f'{args.block_size // 1024}k'
        model_name_suffix = f'_b{block_size_repr}a{anchor_block_size_repr}'
    args.output_dir = os.path.join(args.output_dir, f'{args.model_name}_{args.attn_type}{model_name_suffix}')

    main(
        args.model_path,
        args.attn_type,
        args.block_size,
        args.anchor_block_size,
        args.prompt_config,
        args.max_seq_length,
        args.tasks,
        args.nproc_per_node,
        args.output_dir,
        args.pregen_data_dir,
        num_nodes=args.num_nodes,
    )
